### ISSUE TITLE
Cant work in background

### ISSUE THREAD

**Issue by MasterWolf** [iTXTech/Genisys-Android#1]
When i put Genisys-Android app in background, server crashes...

**Comment by Wolfurama** [comment]
Mine only crashes ir i close window app i just dont close it... Good software the more fast i think :)

**Comment by PeratX** [comment]
I has helped him to fix the problem. Do you have any application which can collect backgroud tasks? Please add Genisys-Android to its white list.

**Comment by Wolfurama** [comment]
I use cleanmaster i just need use it being in the console now you give me that idea i,m very idiot srry (._.)

**Comment by MasterWolf** [comment]
I think we can close this.
