### ISSUE TITLE
[ANDROID] Not working for me :(

### ISSUE THREAD

**Issue by GabiYT** [iTXTech/Genisys-Android#3]
For me, genisys is not working. It says : "Segmentation fault". Please help me

**Comment by ishitatsuyuki** [comment]
You must at least attach a logcat when opening an issue. Issue tracker is not for support request.

**Comment by GabiYT** [comment]
What is a logcat?

**Comment by ishitatsuyuki** [comment]
Please search before asking. REMEMBER, THIS IS NOT FOR SUPPORT REQUEST.

**Comment by zhouruixi** [comment]
I got "Segmentation fault" too with meizu Pro 5 android 5.1 kernel 3.10.61
But it works well with samsung Galaxy S4 android 5.0.1 kernel 3.4.5 except a unzip error(permission denied),and unzip manually
Does it support android X86 ? There is nothing  in Console with Teclast X89 android 4.4.4 kernel 3.10.2 X86_64

I'll show you  the log later

**Comment by zhouruixi** [comment]
[genisys_log.txt](https://github.com/iTXTech/Genisys-Android/files/129129/genisys_log.txt)
This is the LOG of my meizu Pro 5

**Comment by GabiYT** [comment]
@zhouruixi how can i get too the log?

**Comment by zhouruixi** [comment]
@GabiYT run "logcat | grep genisys > /sdcard/log.txt" in terminal

**Comment by GabiYT** [comment]
It isn't work. Oh.. i will abandon it... because   i cant get logcat..  :(

**Comment by GabiYT** [comment]
Btw, my phone is samsung galaxy core prime android 5.1.1

**Comment by PeratX** [comment]
The software does not support x86 and I compiled it on GT-I9500. I cannot made it work with all phones..

**Comment by GabiYT** [comment]
For x86 you can't do this app? Btw, sorry for my english, i'm Romanian.

**Comment by PeratX** [comment]
@GabiYT x86 just can use php7 for linux x86. No need to use this app

**Comment by GabiYT** [comment]
I don't have linux. I don't have host.

**Comment by PeratX** [comment]
Android x86 is linux x86

**Comment by GabiYT** [comment]
Ahh ok. Thanks

**Comment by GabiYT** [comment]
Link to linux x86 plss?

**Comment by zhouruixi** [comment]
Okay,it works now，I just unzip the sourcecode and put php7 for android  into /sdcard/Genisys then use a local terminal with the commond 
cd /sdcard/Genisys 
 ./php  ./src/pocketmine/PocketMine.php

It works well with Meizu Pro 5
May there are something wrong with this app
Thanks for cross ccompile php7 for android!

**Comment by zhouruixi** [comment]
@PeratX There is a interesting thing ，php7 for arm(for android) works with my android X86_64 pad ,but php for linux X86_64 is not work(when I ./php -v ,I got tmp-mksh ./php no such a file or directory)
I really don't know why,it's amazing!

**Comment by GabiYT** [comment]
@zhouruixi for me isn't work. It's says me "Permision denied"

**Comment by zhouruixi** [comment]
@GabiYT  You may need root ,or chmod 777 ./php,if you can't change it ,you can move php to /data,then chmod 777 /data/php with root

**Comment by MasterWolf** [comment]
For me all works great without root!

**Comment by GabiYT** [comment]
@zhouruixi :(( i don't have root and i can't root my phone without PC

**Comment by GabiYT** [comment]
Anyone can help me??

**Comment by MasterWolf** [comment]
oh.. i think i can help

**Comment by MasterWolf** [comment]
you must add permissions for read/write files in your genisys workspace folder.

**Comment by GabiYT** [comment]
@peratx how can i use the files for linux x86 ? Or when you update the app?
