### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys-Android#5]
Genisys Android v0.2.5 alpha
Powered by iTX Technologies

Workspace: /sdcard/Genisys/

a. Init Genisys Android from zips
[NOTICE] Put php.zip and Genisys.zip into /sdcard/Genisys/

Genisys Android v0.2.5 alpha
Powered by iTX Technologies

Workspace: /sdcard/Genisys/

Genisys Android v0.2.5 alpha
Powered by iTX Technologies

Genisys Android v0.2.5 alpha                                Powered by iTX Technologies                                 
Workspace: /sdcard/Genisys/                                 
Genisys Android v0.2.5 alpha                                Powered by iTX Technologies

Workspace: /sdcard/Genisys/                                 
a. Init Genisys Android from zips
[NOTICE] Put php.zip and Genisys.zip into /sdcard/Genisys/  b. Launch Genisys
c. Set workspace                                            d. Edit php.ini
e. Rewrite php.ini
i. About Genisys Android                                    Select: b
[NOTICE] Now loading ...                                    [ERROR] Genisys has not been installed !                    
Press enter to continue ...

**Comment by MasterWolf** [comment]
You must extract genisys from zip and put src folder in /sdcard/Genisys/
Then enter "b" to start server.

**Comment by erkam2002** [comment]
I have it already fixed :)
