### ISSUE TITLE
how to install in intel processor(Zenfone and BlueStacks)

### ISSUE THREAD

**Issue by RedstoneAlmeida** [iTXTech/Genisys-Android#7]

**Comment by PeratX** [comment]
No need

**Comment by MasterWolf** [comment]
LOL dont need to install it on emulators! Just use original genisys. Not android.

**Comment by RedstoneAlmeida** [comment]
"IntelProcessors"
Em 17/03/2016 05:12, "MasterWolf" <notifications@github.com> escreveu:

**Comment by MasterWolf** [comment]
@RedstoneAlmeida emm what do you mean??
